# Generated by Django 5.2.4 on 2025-07-30 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("relationship_app", "0002_alter_book_author_alter_librarian_library_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={
                "permissions": [
                    ("can_add_book", "Can add book"),
                    ("can_change_book", "Can edit book"),
                    ("can_delete_book", "Can delete book"),
                ]
            },
        ),
        migrations.AlterField(
            model_name="library",
            name="books",
            field=models.ManyToManyField(to="relationship_app.book"),
        ),
        migrations.AlterField(
            model_name="library",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("Admin", "Admin"),
                    ("Librarian", "Librarian"),
                    ("Member", "Member"),
                ],
                default="MEMBER",
                max_length=20,
            ),
        ),
    ]
